### ISSUE TITLE
能成功监测到开播状态但是不能开始下载

### ISSUE THREAD

**Issue by Dawnnnnnn** [jf3096/bilibili-live-video-noty#1]
按照说明配置好之后只能检测到是否开播，没办法获取到下载链接，最近B站api进行了一次大的调整，是因为这个吗。。。。。

**Comment by jf3096** [comment]
我最近还在使用，我到明天确定一下回复你把~

_Sent from my Vivo X7Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by xunice13** [comment]
我也是，提示好多一串

**Comment by jf3096** [comment]
@all,
由于12月底B站api进行了调整，主要在于下载的地址需要secret字段。
已修正，已测试一周。
